export const movieMock = {
  page: 1,
  total_results: 1866,
  total_pages: 94,
  results: [
    {
      vote_count: 8494,
      id: 245891,
      video: false,
      vote_average: 7.1,
      title: 'John Wick',
      popularity: 28.082,
      poster_path: '/5vHssUeVe25bMrof1HyaPyWgaP.jpg',
      original_language: 'en',
      original_title: 'John Wick',
      genre_ids: [
        28,
        53,
      ],
      backdrop_path: '/umC04Cozevu8nn3JTDJ1pc7PVTn.jpg',
      adult: false,
      overview: 'Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.',
      release_date: '2014-10-22',
    },
    {
      vote_count: 4314,
      id: 156022,
      video: false,
      vote_average: 7.2,
      title: 'The Equalizer',
      popularity: 26.349,
      poster_path: '/2eQfjqlvPAxd9aLDs8DvsKLnfed.jpg',
      original_language: 'en',
      original_title: 'The Equalizer',
      genre_ids: [
        53,
        28,
        80,
      ],
      backdrop_path: '/hEJ52KqwOmyRpcihs10h7xOwN7e.jpg',
      adult: false,
      overview: 'McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.',
      release_date: '2014-09-24',
    },
    {
      vote_count: 6819,
      id: 244786,
      video: false,
      vote_average: 8.4,
      title: 'Whiplash',
      popularity: 25.862,
      poster_path: '/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg',
      original_language: 'en',
      original_title: 'Whiplash',
      genre_ids: [
        18,
      ],
      backdrop_path: '/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg',
      adult: false,
      overview: 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
      release_date: '2014-10-10',
    },
    {
      vote_count: 8761,
      id: 210577,
      video: false,
      vote_average: 7.9,
      title: 'Gone Girl',
      popularity: 24.946,
      poster_path: '/gdiLTof3rbPDAmPaCf4g6op46bj.jpg',
      original_language: 'en',
      original_title: 'Gone Girl',
      genre_ids: [
        9648,
        53,
        18,
      ],
      backdrop_path: '/8ZNGBfGoN3uI5Akj5vEUDMxvmGO.jpg',
      adult: false,
      overview: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
      release_date: '2014-10-01',
    },
    {
      vote_count: 5823,
      id: 228150,
      video: false,
      vote_average: 7.4,
      title: 'Fury',
      popularity: 21.632,
      poster_path: '/pfte7wdMobMF4CVHuOxyu6oqeeA.jpg',
      original_language: 'en',
      original_title: 'Fury',
      genre_ids: [
        10752,
        18,
        28,
      ],
      backdrop_path: '/pKawqrtCBMmxarft7o1LbEynys7.jpg',
      adult: false,
      overview: 'Last months of World War II in April 1945. As the Allies make their final push in the European Theater, a battle-hardened U.S. Army sergeant in the 2nd Armored Division named Wardaddy commands a Sherman tank called "Fury" and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.',
      release_date: '2014-10-15',
    },
    {
      vote_count: 3393,
      id: 49017,
      video: false,
      vote_average: 6.2,
      title: 'Dracula Untold',
      popularity: 15.782,
      poster_path: '/4oy4e0DP6LRwRszfx8NY8EYBj8V.jpg',
      original_language: 'en',
      original_title: 'Dracula Untold',
      genre_ids: [
        27,
        28,
        18,
        14,
        10752,
      ],
      backdrop_path: '/gy5ItoprIPOT7Z1c2YhNhart39l.jpg',
      adult: false,
      overview: "Vlad Tepes is a great hero, but when he learns the Sultan is preparing for battle and needs to form an army of 1,000 boys, including Vlad's son, he vows to find a way to protect his family. Vlad turns to dark forces in order to get the power to destroy his enemies and agrees to go from hero to monster as he's turned into the mythological vampire Dracula.",
      release_date: '2014-10-01',
    },
    {
      vote_count: 3000,
      id: 200727,
      video: false,
      vote_average: 7.8,
      title: 'Love, Rosie',
      popularity: 10.692,
      poster_path: '/qGYr7P3s0gx5YLvrILnbAkpTt1K.jpg',
      original_language: 'en',
      original_title: 'Love, Rosie',
      genre_ids: [
        35,
        10749,
      ],
      backdrop_path: '/ifokXGHhxSImZKZB4NROO3FN9Ho.jpg',
      adult: false,
      overview: "Since the moment they met at age 5, Rosie and Alex have been best friends, facing the highs and lows of growing up side by side. A fleeting shared moment, one missed opportunity, and the decisions that follow send their lives in completely different directions. As each navigates the complexities of life, love, and everything in between, they always find their way back to each other - but is it just friendship, or something more?  Based on Cecelia Ahern's bestselling novel, LOVE, ROSIE is a heart-warming, modern comedy-of-errors posing the ultimate question: do we really only get one shot at true love?",
      release_date: '2014-10-16',
    },
    {
      vote_count: 2063,
      id: 205587,
      video: false,
      vote_average: 7.3,
      title: 'The Judge',
      popularity: 10.612,
      poster_path: '/v6s65U6qisvxWgO3cNnreaaaite.jpg',
      original_language: 'en',
      original_title: 'The Judge',
      genre_ids: [
        18,
      ],
      backdrop_path: '/wIOR6vXb3SbZw7V7UnbbPTO9wkp.jpg',
      adult: false,
      overview: "A successful lawyer returns to his hometown for his mother's funeral only to discover that his estranged father, the town's judge, is suspected of murder.",
      release_date: '2014-10-08',
    },
    {
      vote_count: 679,
      id: 72784,
      video: false,
      vote_average: 6.4,
      title: 'The Loft',
      popularity: 9.967,
      poster_path: '/9hE6vesQoSREyvJha9z0g5OryHH.jpg',
      original_language: 'en',
      original_title: 'The Loft',
      genre_ids: [
        53,
      ],
      backdrop_path: '/j7qWyikT1eKNezNKxqPkkC8lKz8.jpg',
      adult: false,
      overview: 'For five men, the opportunity to share a penthouse in the city -- in which to carry on extramarital affairs -- is a dream come true, until the dead body of an unknown woman turns up. Realizing that her killer must be one of their group, the men are gripped by paranoia as each one suspects another. Friendships are tested, loyalties are questioned, and marriages crumble while fear and suspicion run rampant.',
      release_date: '2014-10-14',
    },
    {
      vote_count: 1513,
      id: 169917,
      video: false,
      vote_average: 6.3,
      title: 'A Walk Among the Tombstones',
      popularity: 9.777,
      poster_path: '/xxe77USOk2tPnq7G4cL42gf1OxQ.jpg',
      original_language: 'en',
      original_title: 'A Walk Among the Tombstones',
      genre_ids: [
        80,
        18,
        9648,
        53,
      ],
      backdrop_path: '/e56QsaJy1weAUukiK2ZmIGVUALF.jpg',
      adult: false,
      overview: 'Private investigator Matthew Scudder is hired by a drug kingpin to find out who kidnapped and murdered his wife.',
      release_date: '2014-09-18',
    },
    {
      vote_count: 427,
      id: 255343,
      video: false,
      vote_average: 6.3,
      title: 'Escobar: Paradise Lost',
      popularity: 9.76,
      poster_path: '/4HngNLzCmUYCPB8FbxSZWN0eDKM.jpg',
      original_language: 'en',
      original_title: 'Escobar: Paradise Lost',
      genre_ids: [
        53,
        10749,
      ],
      backdrop_path: '/gbwOFHXSLi1DD3D7eI2vlZWIAyq.jpg',
      adult: false,
      overview: "For Pablo Escobar family is everything. When young surfer Nick falls for Escobar's niece, Maria, he finds his life on the line when he's pulled into the dangerous world of the family business.",
      release_date: '2014-10-11',
    },
    {
      vote_count: 381,
      id: 277547,
      video: false,
      vote_average: 5.8,
      title: 'Playing It Cool',
      popularity: 9.439,
      poster_path: '/mBzSxaPOcq8XwXq4qkkyy8Ev9Go.jpg',
      original_language: 'en',
      original_title: 'Playing It Cool',
      genre_ids: [
        35,
        10749,
      ],
      backdrop_path: '/dDxwX9quYcQRaLb8Q5g3owrok9e.jpg',
      adult: false,
      overview: 'The story of a young man disillusioned by love who meets a breathtaking young woman at a charity dinner by pretending to be a philanthropist. Turns out that she’s engaged to a guy who doesn’t like her going on dates. Challenged by the chase, and egged on by his eclectic friends, he feigns a platonic relationship in order to keep seeing her as he tries to conquer her heart',
      release_date: '2014-09-26',
    },
    {
      vote_count: 219,
      id: 254201,
      video: false,
      vote_average: 7.1,
      title: 'The Absent One',
      popularity: 8.235,
      poster_path: '/spvWPsvCi4g3UVDypnQstzPx9Or.jpg',
      original_language: 'da',
      original_title: 'Fasandræberne',
      genre_ids: [
        80,
        53,
        9648,
      ],
      backdrop_path: '/vXuhEarL76D1ijqEK60w6NdHBXm.jpg',
      adult: false,
      overview: 'In 1994 two young twins are found brutally murdered in a summer cottage. A number of clues points in the direction of a group of young upper class students from a nearby boarding school, but the case is closed as a local outsider pleads guilty and is convicted for the murders. When the case ends up on Carls Mørck’s desk 20 years later, he soon realises that something is terribly wrong. As Carl and Assad start investigating the case, they are led on to an old emergency call from a desperate girl who seems to know the secrets of the murders. Soon they are plunged into an intense search for the girl, Kimmie, who has been missing since the murders happened. But Carl and Assad are not the only ones trying to track her down as the girl’s testimonial is of great danger to a group of influential men at the top of society who will do all they can to keep her silent.',
      release_date: '2014-10-02',
    },
    {
      vote_count: 2796,
      id: 250546,
      video: false,
      vote_average: 5.5,
      title: 'Annabelle',
      popularity: 8.168,
      poster_path: '/yAgxM61Sn0dYML4C9v3MJFp5zPI.jpg',
      original_language: 'en',
      original_title: 'Annabelle',
      genre_ids: [
        27,
      ],
      backdrop_path: '/2gKX53lskaCYk9ycXmaDJKqWiy.jpg',
      adult: false,
      overview: "John Form has found the perfect gift for his expectant wife, Mia - a beautiful, rare vintage doll in a pure white wedding dress. But Mia's delight with Annabelle doesn't last long. On one horrific night, their home is invaded by members of a satanic cult, who violently attack the couple. Spilled blood and terror are not all they leave behind. The cultists have conjured an entity so malevolent that nothing they did will compare to the sinister conduit to the damned that is now... Annabelle.",
      release_date: '2014-10-02',
    },
    {
      vote_count: 987,
      id: 239563,
      video: false,
      vote_average: 7.1,
      title: 'St. Vincent',
      popularity: 8.148,
      poster_path: '/w0hzr4eQBk1X4m63fb7sOSt9Bnn.jpg',
      original_language: 'en',
      original_title: 'St. Vincent',
      genre_ids: [
        35,
      ],
      backdrop_path: '/sycS64dwK8eRxMeKALPE29z0HXv.jpg',
      adult: false,
      overview: 'A young boy whose parents just divorced finds an unlikely friend and mentor in the misanthropic, bawdy, hedonistic, war veteran who lives next door.',
      release_date: '2014-10-09',
    },
    {
      vote_count: 878,
      id: 262543,
      video: false,
      vote_average: 5.6,
      title: 'Automata',
      popularity: 7.934,
      poster_path: '/wwo81W8PxHREEprnrJRww471hWm.jpg',
      original_language: 'en',
      original_title: 'Autómata',
      genre_ids: [
        53,
        878,
      ],
      backdrop_path: '/281QVUuSYKBgtdxmr5iAM7YDUZw.jpg',
      adult: false,
      overview: 'Jacq Vaucan, an insurance agent of ROC robotics corporation, routinely investigates the case of manipulating a robot. What he discovers will have profound consequences for the future of humanity.',
      release_date: '2014-10-09',
    },
    {
      vote_count: 603,
      id: 218043,
      video: false,
      vote_average: 3.9,
      title: 'Left Behind',
      popularity: 7.903,
      poster_path: '/lWf8po2lGleVuzRB4lpHavVT1Lv.jpg',
      original_language: 'en',
      original_title: 'Left Behind',
      genre_ids: [
        53,
        28,
        878,
      ],
      backdrop_path: '/oUZn1QXB7FTqMBnM7GdqK5PFNzn.jpg',
      adult: false,
      overview: 'A small group of survivors are left behind after millions of people suddenly vanish during the rapture and the world is plunged into chaos and destruction.',
      release_date: '2014-10-03',
    },
    {
      vote_count: 563,
      id: 244506,
      video: false,
      vote_average: 6.8,
      title: 'Camp X-Ray',
      popularity: 7.894,
      poster_path: '/oGcmIqOAbV8npgY57u7tqzwPgc.jpg',
      original_language: 'en',
      original_title: 'Camp X-Ray',
      genre_ids: [
        18,
      ],
      backdrop_path: '/2R07sv0C7HS1bHdeO5fDfIQplOM.jpg',
      adult: false,
      overview: 'A young woman joins the military to be part of something bigger than herself and her small-town roots. Instead, she ends up as a new guard at Guantanamo Bay, where her mission is far from black and white. Surrounded by hostile jihadists and aggressive squadmates, she strikes up an unusual friendship with one of the detainees.',
      release_date: '2014-10-17',
    },
    {
      vote_count: 198,
      id: 289720,
      video: false,
      vote_average: 4.7,
      title: 'Outcast',
      popularity: 7.748,
      poster_path: '/dUIubxF5osHOJxS3mJNWCqTqWn5.jpg',
      original_language: 'en',
      original_title: 'Outcast',
      genre_ids: [
        28,
      ],
      backdrop_path: '/jmZ8cnELpLGhEEgoRp5QR5VoGyp.jpg',
      adult: false,
      overview: 'A mysterious warrior teams up with the daughter and son of a deposed Chinese Emperor to defeat their cruel Uncle, who seeks their deaths.',
      release_date: '2014-09-26',
    },
    {
      vote_count: 1253,
      id: 239571,
      video: false,
      vote_average: 7.3,
      title: 'The Best of Me',
      popularity: 7.6,
      poster_path: '/449Qq1XKgurG4IFTohtsEuBWJ8H.jpg',
      original_language: 'en',
      original_title: 'The Best of Me',
      genre_ids: [
        18,
        10749,
      ],
      backdrop_path: '/s39ikTKcPr8KNL6PGNCpbq8UxwI.jpg',
      adult: false,
      overview: 'A pair of former high school sweethearts reunite after many years when they return to visit their small hometown.',
      release_date: '2014-10-16',
    },
  ],
};
